update publish.yml

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -54,46 +54,35 @@ jobs:
         name: github-pages
         path: ./public
 
+# Found working solution for hard links and symlinks here: https://github.com/n8design/htwoo/actions/runs/12135102655/workflow
+
   deploy:
+    if: github.repository_owner != 'HugoBlox'
     environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
     runs-on: ubuntu-latest
     needs: build
     steps:
-      - name: Download artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: site
-          path: ./public
-      - name: Cleanup symbolic links in public directory
-        run: find ./public -type l -exec rm -f {} \;
-      - name: Cleanup hard links in public directory
-        run: |
-          if find ./public -type f -links +1 | grep -q .; then
-            find ./public -type f -links +1 -exec rm -f {} \;
-          fi
-      - name: Verify no symbolic links in public directory
-        run: |
-          if find ./public -type l | grep -q .; then
-            echo "Error: Symbolic links found in the public directory."
-            exit 1
-          fi
-      - name: Verify no hard links in public directory
-        run: |
-          if find ./public -type f -links +1 | grep -q .; then
-            echo "Error: Hard links found in the public directory."
-            exit 1
-          fi
-      - name: List current folders
-        run: ls -la ./public
-      - name: Setup Pages
-        uses: actions/configure-pages@v5
-      - name: Upload artifact
-        uses: actions/upload-pages-artifact@v3
-        with:
-          name: github-pages
-          path: './public'
-      - name: Deploy to GitHub Pages
-        id: deployment
-        uses: actions/deploy-pages@v4
+    - name: Cleanup symbolic links in public directory
+      run: find ./public -type l -exec rm -f {} \;
+    - name: Cleanup hard links in public directory
+      run: |
+        if find ./public -type f -links +1 | grep -q .; then
+          find ./public -type f -links +1 -exec rm -f {} \;
+        fi
+    - name: Verify no symbolic links in public directory
+      run: |
+        if find ./public -type l | grep -q .; then
+          echo "Error: Symbolic links found in the public directory."
+          exit 1
+        fi
+    - name: Verify no hard links in public directory
+      run: |
+        if find ./public -type f -links +1 | grep -q .; then
+          echo "Error: Hard links found in the public directory."
+          exit 1
+        fi
+    - name: Deploy to GitHub Pages
+      id: deployment
+      uses: actions/deploy-pages@v4
